"""add Department

Revision ID: 92022026a17b
Revises: e3a87eb121b7
Create Date: 2025-01-06 15:09:34.853072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92022026a17b'
down_revision = 'e3a87eb121b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
